# -*- coding: utf-8 -*-
"""Python code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11rAmL46ROabjmO18hmccmBKp4cF5b48R
"""

x = 10
y = 50
if (x ** 2 > 100 and y < 100):
    print(x, y)